/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include "app.hpp"

using namespace std;
using namespace ovd;

int main () {
    Greeter greeter;
    cout << greeter.greeting() << endl;
    return 0;
}
