/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef APP_H
#define APP_H

#include <string>
using namespace std;

namespace ovd {
    class Greeter {
        public:
        string greeting() {
            return "Hello World";
        }
    };
}

#endif
